import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/NavBar";
import HeroSection from "./components/HeroSection";
import FeaturedReleases from "./components/FeaturedReleases";
import SecondHeroSection from "./components/SecondHeroSection";
import BestSellers from "./components/BestSellers";
import Categories from "./components/Categories";
import StayInTheLoop from "./components/StayInTheLoop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="">
          <Navbar />
        </div>
        <HeroSection />

        <div className="py-12">
          <FeaturedReleases />
        </div>

        <div className="py-12">
          <SecondHeroSection />
        </div>

        <div className="py-12">
          <BestSellers />
        </div>

        <div className="py-12">
          <Categories />
        </div>

        <div>
          <StayInTheLoop />
        </div>
      </body>
    </html>
  );
}
